### ISSUE TITLE
Erratic behaviour with Alt + F4 in full screen

### ISSUE THREAD

**Issue by kehugter** [xylosper/bomi#183]
In full screen, pressing `Alt + F4` re-opens the window instead of closing it, the same that happens with `CTRL + W`. Out of full screen, `Alt + F4` closes bomi to the tray.

After `Alt + F4`, the ability to exit full screen with `Enter` is lost (although sometimes comes back after trying long enough). After trying to reproduce the problem a dozen of times, I can't exit the full screen any more (`Enter`, double-click and `Window -> Maximize` fail). Launching in verbose + debug mode doesn't log anything out of the ordinary. In particular, nothing is written if I hit `Enter` trying to exit full screen.

(could you also tell me how to fix bomi in my computer?)

**Comment by xylosper** [comment]
Fixed. Thank you.

**Comment by kehugter** [comment]
Thanks for your quick responses!

**Comment by kehugter** [comment]
I'm stuck at this, I can't exit the full screen any more. bomi originally installed via apt repo, running Linux Mint 17.1. Tried removing, purging and re-installing, didn't work. I also tried to build from the source, but I'm in a 3rd-level sub-dependency installation and still getting missing packages, so I'm afraid that I'll break more stuff in the process.

My guess is that my full screen issue is something related to qt, but I don't know how to debug that, nor do I know what to search for. Could you give me a hint on how to go on?

(posting it as part of this issue, since the cause has already been fixed)

**Comment by xylosper** [comment]
PPA is not updated yet. If you want to build bomi with latest source, you'd better see the contorls and rules file in debian folder. Also, read https://github.com/xylosper/bomi/wiki/Build-and-install-from-source-code#compilation .

**Comment by kehugter** [comment]
Yes, I went trough the guide in the wiki, but there were many other unmet dependencies (not fixed by the ffmpeg and libchardet scripts).

I'll wait for the PPA update then and report back.

**Comment by xylosper** [comment]
All dependencies are written in controls file and what you have to specify is written rules file.

**Comment by kehugter** [comment]
Ok, I got trough the configure script. I had to change this line https://github.com/xylosper/bomi/blob/master/configure#L143 to

    if [ -z "$qmake" ]; then qmake="qmake -qt5"; fi

taking this issue as reference https://github.com/andrewd18/df-lnp-installer/issues/65

On `make`, I get

    Build failed
    -> task in 'mpv' failed (exit status 1): 
        {task 47076873019984: c audio.c -> audio.c.13.o}
    ['/usr/bin/cc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wno-parentheses', '-Wpointer-arith', '-Wredundant-decls', '-Wno-pointer-sign', '-pthread', '-pthread', '-I/home/me/opt/bomi/src/mpv/build', '-I/home/me/opt/bomi/src/mpv', '-I/home/me/Downloads/bomi/build/include', '-I/usr/include/alsa', '-I/usr/include/harfbuzz', '-I/usr/include/freetype2', '-I/usr/include/fribidi', '-DHAVE_VAAPI_GLX=1', '-DHAVE_DVDNAV=1', '-DHAVE_DVDREAD=1', '-DHAVE_LIBSWRESAMPLE=1', '-DHAVE_LIBAV=1', '-DHAVE_MPG123=1', '-DHAVE_VAAPI=1', '-DHAVE_ALSA=1', '-DHAVE_LIBBLURAY=1', '-DPATH_DEV_DSP="/dev/dsp"', '-DPATH_DEV_MIXER="/dev/mixer"', '-DHAVE_VDPAU=1', '-DHAVE_X11=1', '-DHAVE_LIBASS=1', '../audio/audio.c', '-c', '-o', '/home/me/opt/bomi/src/mpv/build/audio/audio.c.13.o']

**Comment by xylosper** [comment]
No you don't. Did you read `rules` file?
